### ISSUE TITLE
Overlay - Evento Blockchain Rio 2023 • Cardano

### ISSUE THREAD

**Issue by bellaamaral** [ioxtream/overlayx#25]
Overlay para a live stream do evento da Cardano no Blockchain Rio Festival 2023.

**Comment by bellaamaral** [comment]
### Link do Drive para o Overlay:
https://drive.google.com/drive/folders/1RqHpZGfuXeliL3JU3I4VMa78GGDpyl8n?usp=drive_link
 
-----------------------------------
 

_OBS.: O GitHub não aceita o formato .mov, por isso o arquivo está no Drive._

**Comment by zero-complexity** [comment]
O overlay já está sendo utilizado.
